# Generated by Django 3.2.15 on 2022-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='password2',
        ),
    ]
