# Generated by Django 3.2.15 on 2022-08-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_information_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
