# Generated by Django 3.2.15 on 2022-08-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220822_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='User',
        ),
    ]
